/**
 * Centralized Demo Data Layer for Web Starzz
 * 
 * Realistic developer/application session data with structured flow,
 * client environment metadata, and error metrics.
 */

export const mockSessions = [
  {
    sessionId: "sess_9f83a12b",
    startedAt: "2026-09-22T22:45:12Z",
    duration: 342, // seconds
    eventCount: 68,
    errorCount: 3,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "macOS",
    device: "Desktop",
    lastPage: "/checkout/payment",
    status: "error",
    userFlow: ["/home", "/products/app-gateway", "/cart", "/checkout/shipping", "/checkout/payment"],
    errorMessage: "Unhandled Promise Rejection: Payment Gateway Timeout (504)",
    userId: "usr_dev_402"
  },
  {
    sessionId: "sess_4k72m9p1",
    startedAt: "2026-09-22T22:30:00Z",
    duration: 185,
    eventCount: 42,
    errorCount: 0,
    browser: "Firefox",
    browserVersion: "130.0",
    operatingSystem: "Windows",
    device: "Desktop",
    lastPage: "/dashboard/analytics",
    status: "normal",
    userFlow: ["/login", "/dashboard", "/dashboard/analytics"],
    userId: "usr_dev_108"
  },
  {
    sessionId: "sess_1c84f6e3",
    startedAt: "2026-09-22T22:15:45Z",
    duration: 512,
    eventCount: 104,
    errorCount: 1,
    browser: "Safari",
    browserVersion: "17.5",
    operatingSystem: "iOS",
    device: "Mobile",
    lastPage: "/upload/assets",
    status: "warning",
    userFlow: ["/home", "/dashboard", "/upload", "/upload/assets"],
    errorMessage: "Warning: Chunk size exceeds recommended limit (4.2MB)",
    userId: "usr_mob_882"
  },
  {
    sessionId: "sess_7b9021da",
    startedAt: "2026-09-22T21:58:20Z",
    duration: 94,
    eventCount: 18,
    errorCount: 0,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "Android",
    device: "Mobile",
    lastPage: "/products/serverless-db",
    status: "normal",
    userFlow: ["/home", "/products/serverless-db"],
    userId: "usr_mob_119"
  },
  {
    sessionId: "sess_3e51c890",
    startedAt: "2026-09-22T21:42:10Z",
    duration: 620,
    eventCount: 142,
    errorCount: 5,
    browser: "Chrome",
    browserVersion: "127.0.6533",
    operatingSystem: "Windows",
    device: "Desktop",
    lastPage: "/settings/api-keys",
    status: "error",
    userFlow: ["/login", "/settings", "/settings/api-keys"],
    errorMessage: "TypeError: Cannot read property 'permissions' of undefined",
    userId: "usr_admin_001"
  },
  {
    sessionId: "sess_6a12d45e",
    startedAt: "2026-09-22T21:20:00Z",
    duration: 230,
    eventCount: 51,
    errorCount: 0,
    browser: "Edge",
    browserVersion: "128.0.2739",
    operatingSystem: "Windows",
    device: "Desktop",
    lastPage: "/docs/api-reference",
    status: "normal",
    userFlow: ["/home", "/docs", "/docs/api-reference"],
    userId: "usr_guest_901"
  },
  {
    sessionId: "sess_8c34e71f",
    startedAt: "2026-09-22T21:05:30Z",
    duration: 410,
    eventCount: 89,
    errorCount: 2,
    browser: "Firefox",
    browserVersion: "129.0",
    operatingSystem: "Linux",
    device: "Desktop",
    lastPage: "/projects/build-logs",
    status: "error",
    userFlow: ["/dashboard", "/projects", "/projects/build-logs"],
    errorMessage: "WebSocket Connection Failed: wss://stream.starzz.io/logs (502)",
    userId: "usr_dev_314"
  },
  {
    sessionId: "sess_2f91a54b",
    startedAt: "2026-09-22T20:50:15Z",
    duration: 145,
    eventCount: 29,
    errorCount: 0,
    browser: "Safari",
    browserVersion: "17.4",
    operatingSystem: "macOS",
    device: "Desktop",
    lastPage: "/billing/invoices",
    status: "normal",
    userFlow: ["/settings", "/billing", "/billing/invoices"],
    userId: "usr_fin_220"
  },
  {
    sessionId: "sess_5d09b23c",
    startedAt: "2026-09-22T20:30:00Z",
    duration: 78,
    eventCount: 16,
    errorCount: 1,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "Android",
    device: "Mobile",
    lastPage: "/login",
    status: "warning",
    userFlow: ["/login"],
    errorMessage: "AuthRateLimitExceeded: Too many failed login attempts",
    userId: "usr_unknown"
  },
  {
    sessionId: "sess_0e76f18a",
    startedAt: "2026-09-22T20:12:40Z",
    duration: 890,
    eventCount: 195,
    errorCount: 0,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "macOS",
    device: "Desktop",
    lastPage: "/investigations/trace-902",
    status: "normal",
    userFlow: ["/dashboard", "/investigations", "/investigations/trace-902"],
    userId: "usr_sre_007"
  },
  {
    sessionId: "sess_9d21c43f",
    startedAt: "2026-09-22T19:55:00Z",
    duration: 310,
    eventCount: 62,
    errorCount: 0,
    browser: "Safari",
    browserVersion: "17.5",
    operatingSystem: "iOS",
    device: "Tablet",
    lastPage: "/dashboard/metrics",
    status: "normal",
    userFlow: ["/login", "/dashboard", "/dashboard/metrics"],
    userId: "usr_mgr_405"
  },
  {
    sessionId: "sess_4a53b87e",
    startedAt: "2026-09-22T19:40:22Z",
    duration: 475,
    eventCount: 96,
    errorCount: 4,
    browser: "Firefox",
    browserVersion: "130.0",
    operatingSystem: "Windows",
    device: "Desktop",
    lastPage: "/deployments/production",
    status: "error",
    userFlow: ["/dashboard", "/deployments", "/deployments/production"],
    errorMessage: "Failed to load chunk 404: Script load error",
    userId: "usr_dev_108"
  },
  {
    sessionId: "sess_7e82f901",
    startedAt: "2026-09-22T19:25:10Z",
    duration: 160,
    eventCount: 35,
    errorCount: 0,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "Windows",
    device: "Desktop",
    lastPage: "/docs/getting-started",
    status: "normal",
    userFlow: ["/home", "/docs", "/docs/getting-started"],
    userId: "usr_guest_114"
  },
  {
    sessionId: "sess_1d94a65b",
    startedAt: "2026-09-22T19:10:00Z",
    duration: 270,
    eventCount: 54,
    errorCount: 1,
    browser: "Edge",
    browserVersion: "128.0.2739",
    operatingSystem: "Windows",
    device: "Desktop",
    lastPage: "/team/members",
    status: "warning",
    userFlow: ["/settings", "/team", "/team/members"],
    errorMessage: "Warning: Slow response time from /api/v1/team (1420ms)",
    userId: "usr_admin_002"
  },
  {
    sessionId: "sess_3c15e892",
    startedAt: "2026-09-22T18:45:30Z",
    duration: 120,
    eventCount: 24,
    errorCount: 0,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "macOS",
    device: "Desktop",
    lastPage: "/profile",
    status: "normal",
    userFlow: ["/login", "/profile"],
    userId: "usr_dev_551"
  },
  {
    sessionId: "sess_6f28b40d",
    startedAt: "2026-09-22T18:30:15Z",
    duration: 530,
    eventCount: 118,
    errorCount: 2,
    browser: "Chrome",
    browserVersion: "127.0.6533",
    operatingSystem: "Linux",
    device: "Desktop",
    lastPage: "/database/clusters",
    status: "error",
    userFlow: ["/dashboard", "/database", "/database/clusters"],
    errorMessage: "NetworkError: CORS header 'Access-Control-Allow-Origin' missing",
    userId: "usr_dev_314"
  },
  {
    sessionId: "sess_8b41f763",
    startedAt: "2026-09-22T18:00:00Z",
    duration: 215,
    eventCount: 48,
    errorCount: 0,
    browser: "Safari",
    browserVersion: "17.4",
    operatingSystem: "macOS",
    device: "Desktop",
    lastPage: "/security/audit-logs",
    status: "normal",
    userFlow: ["/settings", "/security", "/security/audit-logs"],
    userId: "usr_sec_990"
  },
  {
    sessionId: "sess_0a92d31c",
    startedAt: "2026-09-22T17:40:10Z",
    duration: 380,
    eventCount: 76,
    errorCount: 0,
    browser: "Firefox",
    browserVersion: "129.0",
    operatingSystem: "Windows",
    device: "Desktop",
    lastPage: "/integrations/webhooks",
    status: "normal",
    userFlow: ["/settings", "/integrations", "/integrations/webhooks"],
    userId: "usr_dev_402"
  },
  {
    sessionId: "sess_5f30e921",
    startedAt: "2026-09-22T17:15:00Z",
    duration: 95,
    eventCount: 20,
    errorCount: 1,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "Android",
    device: "Mobile",
    lastPage: "/checkout/confirmation",
    status: "warning",
    userFlow: ["/cart", "/checkout", "/checkout/confirmation"],
    errorMessage: "DeprecationWarning: Synchronous XMLHttpRequest on main thread",
    userId: "usr_mob_330"
  },
  {
    sessionId: "sess_2b74c51e",
    startedAt: "2026-09-22T16:50:30Z",
    duration: 640,
    eventCount: 135,
    errorCount: 0,
    browser: "Chrome",
    browserVersion: "128.0.6613",
    operatingSystem: "macOS",
    device: "Desktop",
    lastPage: "/performance/waterfall",
    status: "normal",
    userFlow: ["/dashboard", "/performance", "/performance/waterfall"],
    userId: "usr_sre_007"
  },
  {
    sessionId: "sess_4d18a93b",
    startedAt: "2026-09-22T16:20:00Z",
    duration: 415,
    eventCount: 82,
    errorCount: 3,
    browser: "Safari",
    browserVersion: "17.5",
    operatingSystem: "iOS",
    device: "Mobile",
    lastPage: "/api/v2/graphql",
    status: "error",
    userFlow: ["/home", "/api/v2/graphql"],
    errorMessage: "GraphQL Syntax Error: Expected Name, found String 'query'",
    userId: "usr_mob_702"
  },
  {
    sessionId: "sess_9e01f24c",
    startedAt: "2026-09-22T15:45:10Z",
    duration: 290,
    eventCount: 60,
    errorCount: 0,
    browser: "Firefox",
    browserVersion: "130.0",
    operatingSystem: "Linux",
    device: "Desktop",
    lastPage: "/monitoring/alerts",
    status: "normal",
    userFlow: ["/dashboard", "/monitoring", "/monitoring/alerts"],
    userId: "usr_dev_314"
  }
];

export const mockActivities = [
  {
    id: "act_101",
    timestamp: "2026-09-22T22:45:12Z",
    sessionId: "sess_9f83a12b",
    type: "error",
    title: "Payment Gateway Timeout",
    message: "Session sess_9f83a12b hit 504 Gateway Timeout at /checkout/payment",
    path: "/checkout/payment"
  },
  {
    id: "act_102",
    timestamp: "2026-09-22T21:42:10Z",
    sessionId: "sess_3e51c890",
    type: "error",
    title: "TypeError in Permissions Component",
    message: "Cannot read property 'permissions' of undefined at /settings/api-keys",
    path: "/settings/api-keys"
  },
  {
    id: "act_103",
    timestamp: "2026-09-22T21:05:30Z",
    sessionId: "sess_8c34e71f",
    type: "error",
    title: "WebSocket Connection Failed",
    message: "wss://stream.starzz.io/logs returned status 502 (Bad Gateway)",
    path: "/projects/build-logs"
  },
  {
    id: "act_104",
    timestamp: "2026-09-22T20:30:00Z",
    sessionId: "sess_5d09b23c",
    type: "warning",
    title: "Auth Rate Limit Warning",
    message: "Rate limit warning triggered for user login attempts",
    path: "/login"
  },
  {
    id: "act_105",
    timestamp: "2026-09-22T20:12:40Z",
    sessionId: "sess_0e76f18a",
    type: "info",
    title: "High Event Density Recorded",
    message: "Session sess_0e76f18a recorded 195 events over 14 minutes",
    path: "/investigations/trace-902"
  },
  {
    id: "act_106",
    timestamp: "2026-09-22T19:40:22Z",
    sessionId: "sess_4a53b87e",
    type: "error",
    title: "Chunk Load Failure",
    message: "Failed to load asset chunk 404 at /deployments/production",
    path: "/deployments/production"
  }
];
